# -*- coding: utf-8 -*-
"""Google Search Analysis with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9E9J2FztNH7ixKqdKmkkf_hiVfBzuFY

# **Google Search Analysis with Python**

Google doesn’t give much access to the data about daily search queries, but another application of google known as Google Trends can be used for the task of Google search analysis. Google Trends offers an API that allows us to perform Google search analysis. This API can be accessed using the pytrends library, which can be easily installed using the command pip install pytrends.

Importing pytrends
"""

!pip install pytrends

"""Google search analysis by importing the necessary Python libraries:"""

import pandas as pd
from pytrends.request import TrendReq
import matplotlib.pyplot as plt
trends = TrendReq()

"""# **Analyzing Google Search Trends**

Here I will be analyzing the Google search trends on the queries based on “Data Analytics”, so let’s create a DataFrame of the top 10 countries which search for “Data Analytics” on Google:
"""

trends.build_payload(kw_list=["Data Analytics"])
data = trends.interest_by_region()
data = data.sort_values(by="Data Analytics", ascending=False)
data = data.head(10)
print(data)

"""So, according to the above results, the search queries based on “Data Analytics” are mostly done in Singapore.

# **Visualizing the Data**

We can also visualize this data using a bar chart:
"""

data.reset_index().plot(x="geoName",
                        y="Data Analytics",
                        figsize=(15,12), kind="bar")
plt.style.use('fivethirtyeight')
plt.xlabel('Region')
plt.ylabel('Search Interest')
plt.title('Top 10 Regions by Search Interest in Data Analytics')
plt.show()

"""# **Analyzing Trends Over Time**

So as we all know that Data Analytics has been the focus of so many companies and students for the last 3-4 years, so let’s have a look at the trend of searches to see how the total search queries based on “Data Analytics” increased or decreased on Google:
"""

data = TrendReq(hl='en-US', tz=360)
data.build_payload(kw_list=['Data Analytics'])
data = data.interest_over_time()
fig, ax = plt.subplots(figsize=(15, 12))
data['Data Analytics'].plot()
plt.style.use('fivethirtyeight')
plt.title('Total Google Searches for Data Analytics',
          fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Total Count')
plt.show()

"""# **Conclusion**

so we can see a huge increase in the searches about “Data Analytics” on Google in 2022 to 2024. Analyzing Google searches based on keywords can provide valuable insights for businesses and researchers. A business can perform Google search analysis to understand what people are looking for on Google at any given time. By leveraging Python and tools like pytrends, we can perform in-depth analysis and track trends over time, helping us understand user behavior and interests.
"""